"""
Stage 0 — Corpus audit.

Confirms the 66-study primary corpus, maps each source PDF to its Study_ID
from EMSE_MASTER_REFERENCE_v6_4_FINAL.xlsx ("Master Data" sheet), and records
per-study checksums, duplicate checks, and raw (pre-preprocessing) document
length in tokens.

Per PRE_EXECUTION_ANALYSIS_PLAN.md §1. Deterministic; no LDA fitting here.
"""

from __future__ import annotations

import csv
import difflib
import hashlib
import re
import unicodedata
from pathlib import Path

import fitz  # PyMuPDF
import numpy as np
import openpyxl
from scipy.optimize import linear_sum_assignment

# Manual verification log for PDF<->Study_ID matches that scored below the
# "high" title-similarity threshold (title-match ratio alone is a weak
# signal for truncated/abbreviated filenames or preprint-vs-camera-ready
# title changes). Each entry below was independently checked against the
# PDF content (author list and/or full title substring) before this script
# was frozen -- see corpus/corpus_audit.md history for the pre-verification
# ratios. This is a fixed, deterministic override list, not a per-run guess.
MANUALLY_VERIFIED_MATCHES = {
    "S65": "PDF filename 'HAVEN' is a truncation of the master title "
           "'HAVEN: Hallucination-Mitigated LLM for Verilog Code Generation...'.",
    "S66": "PDF filename 'Importing Phantoms' is a truncation of the master title "
           "'Importing Phantoms: Measuring LLM Package Hallucination Vulnerabilities'.",
    "S23": "PDF filename 'CodeHalu Investigating' is a truncation of the master title "
           "'CodeHalu: Investigating Code Hallucinations in LLMs via Execution-based Verification'.",
    "S36": "PDF is a preprint titled 'Exploring and Evaluating Hallucinations in "
           "LLM-Powered Code Generation'; master title is the camera-ready title "
           "'Beyond Functional Correctness: Exploring Hallucinations in LLM-Generated Code'. "
           "Confirmed identical via author list: Fang Liu, Yang Liu, Lin Shi, Houkun Huang, "
           "Ruifeng Wang, Zhen Yang, Li Zhang, Zhongqi Li, Yuchi Ma (exact match on both).",
    "S34": "PDF filename is a truncation of the master title "
           "'Experiences and Challenges in AI-Driven Modular Software Development Using "
           "Large Language Models for Code Generation'.",
    "S43": "PDF filename is a truncation of the master title "
           "'Fight Fire with Fire: How Much Can We Trust ChatGPT on Source Code-Related Tasks?'.",
    "S33": "PDF filename is a truncation of the master title "
           "'Expectation vs. Experience: Evaluating the Usability of Code Generation Tools "
           "Powered by Large Language Models'.",
    "S70": "PDF filename (with numeric prefix '6-') is a truncation of the master title "
           "'Towards Mitigating API Hallucination in Code Generated by LLMs with Hierarchical "
           "Dependency Aware'.",
}

ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = ROOT.parent  # .../Final Copy
MASTER_XLSX = PROJECT_ROOT / "EMSE_MASTER_REFERENCE_v6_4_FINAL.xlsx"
PDF_DIR = ROOT / "66_Primery_Study"
OUT_CSV = ROOT / "corpus" / "corpus_audit.csv"
OUT_MD = ROOT / "corpus" / "corpus_audit.md"


def normalize_title(s: str) -> str:
    s = unicodedata.normalize("NFKC", s)
    s = s.lower()
    # strip a leading "<number>- " filename prefix (e.g. "1- Code Generation...")
    s = re.sub(r"^\s*\d+\s*-\s*", "", s)
    s = re.sub(r"\.pdf$", "", s, flags=re.IGNORECASE)
    s = re.sub(r"[^a-z0-9]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def load_primary_studies() -> list[dict]:
    wb = openpyxl.load_workbook(MASTER_XLSX, data_only=True)
    ws = wb["Master Data"]
    rows = list(ws.iter_rows(values_only=True))
    header = rows[0]
    idx = {h: i for i, h in enumerate(header)}
    studies = []
    for r in rows[1:]:
        if r[idx["Study category"]] == "Primary":
            studies.append(
                {
                    "Study_ID": r[idx["Study ID"]],
                    "title": r[idx["Title"]],
                    "authors": r[idx["Authors"]],
                    "year": r[idx["Year"]],
                    "venue": r[idx["Venue"]],
                }
            )
    return studies


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def raw_token_count(path: Path) -> tuple[int, int]:
    """Returns (char_count, whitespace_token_count) of raw extracted text, all pages."""
    doc = fitz.open(path)
    text = "\n".join(page.get_text() for page in doc)
    doc.close()
    chars = len(text)
    tokens = len(text.split())
    return chars, tokens


def optimal_assignment(pdf_paths: list[Path], studies: list[dict]) -> list[tuple[Path, dict, float]]:
    """
    One-to-one PDF<->Study_ID assignment maximizing total title-similarity,
    via Hungarian algorithm (scipy.optimize.linear_sum_assignment) on the
    full similarity matrix -- avoids the many-to-one collisions that
    independent per-PDF argmax matching produces.
    """
    n = len(pdf_paths)
    m = len(studies)
    sim = np.zeros((n, m))
    pdf_norms = [normalize_title(p.stem) for p in pdf_paths]
    study_norms = [normalize_title(s["title"]) for s in studies]
    for i, pn in enumerate(pdf_norms):
        for j, sn in enumerate(study_norms):
            sim[i, j] = difflib.SequenceMatcher(None, pn, sn).ratio()

    row_ind, col_ind = linear_sum_assignment(-sim)  # maximize similarity
    assignment = []
    for i, j in zip(row_ind, col_ind):
        assignment.append((pdf_paths[i], studies[j], sim[i, j]))
    return assignment


def main() -> None:
    studies = load_primary_studies()
    assert len(studies) == 66, f"Expected 66 Primary studies, found {len(studies)}"

    pdf_paths = sorted(PDF_DIR.glob("*.pdf"))
    assert len(pdf_paths) == 66, f"Expected 66 PDFs, found {len(pdf_paths)}"

    assignment = optimal_assignment(pdf_paths, studies)

    rows = []
    hash_to_pdfs: dict[str, list[str]] = {}
    assigned_study_ids: dict[str, str] = {}  # Study_ID -> pdf filename

    for pdf_path, study, ratio in assignment:
        raw_confidence = "high" if ratio >= 0.85 else ("medium" if ratio >= 0.55 else "low")
        sid = study["Study_ID"]
        manual_note = MANUALLY_VERIFIED_MATCHES.get(sid, "")
        confidence = "high (manually verified)" if manual_note else raw_confidence

        digest = sha256_of(pdf_path)
        hash_to_pdfs.setdefault(digest, []).append(pdf_path.name)

        chars, tokens = raw_token_count(pdf_path)

        row = {
            "Study_ID": sid,
            "pdf_filename": pdf_path.name,
            "master_title": study["title"],
            "year": study["year"],
            "venue": study["venue"],
            "title_match_ratio": round(ratio, 4),
            "match_confidence": confidence,
            "manual_verification_note": manual_note,
            "sha256": digest,
            "raw_char_count": chars,
            "raw_token_count": tokens,
        }
        rows.append(row)

        if study["Study_ID"] in assigned_study_ids:
            row["DUPLICATE_ASSIGNMENT_WARNING"] = (
                f"Study_ID already assigned to {assigned_study_ids[study['Study_ID']]}"
            )
        assigned_study_ids[study["Study_ID"]] = pdf_path.name

    # Integrity checks
    unique_study_ids = {r["Study_ID"] for r in rows}
    duplicate_hashes = {h: fs for h, fs in hash_to_pdfs.items() if len(fs) > 1}
    unverified_low_conf = [
        r for r in rows
        if r["match_confidence"] not in ("high",) and not r["manual_verification_note"]
    ]
    manually_verified = [r for r in rows if r["manual_verification_note"]]

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "Study_ID", "pdf_filename", "master_title", "year", "venue",
        "title_match_ratio", "match_confidence", "manual_verification_note", "sha256",
        "raw_char_count", "raw_token_count", "DUPLICATE_ASSIGNMENT_WARNING",
    ]
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in sorted(rows, key=lambda x: x["Study_ID"]):
            w.writerow(r)

    tokens_list = [r["raw_token_count"] for r in rows]
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write("# Corpus Audit — 66 Primary Studies\n\n")
        f.write(f"- PDFs found in `66_Primery_Study/`: **{len(pdf_paths)}**\n")
        f.write(f"- Primary studies in Master Data: **{len(studies)}**\n")
        f.write(f"- Unique Study_IDs assigned: **{len(unique_study_ids)}**\n")
        f.write(f"- Duplicate-content PDFs (identical SHA-256): **{len(duplicate_hashes)}**\n")
        f.write(f"- Low title-similarity matches, manually verified (author list / substring): "
                f"**{len(manually_verified)}**\n")
        f.write(f"- Unverified low-confidence matches remaining: **{len(unverified_low_conf)}**\n\n")
        f.write(f"- Raw token count — min {min(tokens_list)}, max {max(tokens_list)}, "
                f"mean {sum(tokens_list)/len(tokens_list):.0f}\n\n")

        if manually_verified:
            f.write("## Low title-similarity matches — manually verified\n\n")
            f.write("These PDF filenames are truncated or use a preprint title different from the "
                    "master (camera-ready) title, so the automated string-similarity ratio is low. "
                    "Each was independently confirmed correct (see `manual_verification_note`).\n\n")
            f.write("| Study_ID | pdf_filename | master_title | ratio | note |\n")
            f.write("|---|---|---|---|---|\n")
            for r in sorted(manually_verified, key=lambda x: x["title_match_ratio"]):
                f.write(f"| {r['Study_ID']} | {r['pdf_filename']} | {r['master_title']} | "
                        f"{r['title_match_ratio']} | {r['manual_verification_note']} |\n")
            f.write("\n")

        if unverified_low_conf:
            f.write("## WARNING: unverified non-high-confidence matches\n\n")
            f.write("| Study_ID | pdf_filename | master_title | ratio | confidence |\n")
            f.write("|---|---|---|---|---|\n")
            for r in sorted(unverified_low_conf, key=lambda x: x["title_match_ratio"]):
                f.write(f"| {r['Study_ID']} | {r['pdf_filename']} | {r['master_title']} | "
                        f"{r['title_match_ratio']} | {r['match_confidence']} |\n")
            f.write("\n")

        if duplicate_hashes:
            f.write("## WARNING: duplicate PDF content detected\n\n")
            for h, fs in duplicate_hashes.items():
                f.write(f"- `{h[:12]}...`: {fs}\n")
            f.write("\n")

        f.write("## Full mapping\n\n")
        f.write("| Study_ID | pdf_filename | ratio | confidence | raw_tokens |\n")
        f.write("|---|---|---|---|---|\n")
        for r in sorted(rows, key=lambda x: x["Study_ID"]):
            f.write(f"| {r['Study_ID']} | {r['pdf_filename']} | {r['title_match_ratio']} | "
                    f"{r['match_confidence']} | {r['raw_token_count']} |\n")

    print(f"Studies: {len(studies)} | PDFs: {len(pdf_paths)} | Unique Study_IDs assigned: {len(unique_study_ids)}")
    print(f"Duplicate-hash groups: {len(duplicate_hashes)}")
    print(f"Manually verified low-similarity matches: {len(manually_verified)}")
    print(f"Unverified low-confidence matches: {len(unverified_low_conf)}")
    if len(unique_study_ids) != 66:
        missing = {s["Study_ID"] for s in studies} - unique_study_ids
        print(f"MISSING Study_IDs (no PDF matched): {sorted(missing)}")
    print(f"Wrote {OUT_CSV}")
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
